// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/knowledge/sync": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台管理"
                ],
                "summary": "同步知识库来源",
                "parameters": [
                    {
                        "description": "json入参",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admintype.SyncKnowledgeRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/admin/role-mappings": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台管理"
                ],
                "summary": "创建或保存角色映射规则",
                "parameters": [
                    {
                        "description": "json入参",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admintype.CreateRoleMappingRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/admin/role-owners": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台管理"
                ],
                "summary": "角色负责人列表",
                "responses": {}
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台管理"
                ],
                "summary": "保存角色负责人",
                "parameters": [
                    {
                        "description": "json入参",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admintype.SaveRoleOwnerRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/auth/feishu/config": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "获取飞书 SSO 前端配置",
                "responses": {}
            }
        },
        "/api/auth/feishu/sso/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "飞书 SSO 登录",
                "parameters": [
                    {
                        "description": "json入参",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authtype.FeishuSSOLoginRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/auth/logout": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "登出",
                "responses": {}
            }
        },
        "/api/checkpoints/{checkpointID}/approve": {
            "post": {
                "description": "对 pending 且绑定到 waiting_approval Run/Stage 的 checkpoint 做 approve 决策。审批通过后 checkpoint stage 会标记 succeeded，PipelineRun 重新 queued 并继续后续阶段；重复审批会被拒绝。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Checkpoint"
                ],
                "summary": "审批通过检查点",
                "parameters": [
                    {
                        "type": "string",
                        "description": "检查点ID",
                        "name": "checkpointID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "json入参",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.UpdateCheckpointDecisionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.CheckpointEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/checkpoints/{checkpointID}/reject": {
            "post": {
                "description": "对 pending 且绑定到 waiting_approval Run/Stage 的 checkpoint 做 reject 决策。驳回后会回退到上一可执行阶段，携带 reject comment 作为重做上下文，并将后续阶段与产物标记为待重跑/已 superseded。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Checkpoint"
                ],
                "summary": "驳回检查点",
                "parameters": [
                    {
                        "type": "string",
                        "description": "检查点ID",
                        "name": "checkpointID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "json入参",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.UpdateCheckpointDecisionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.CheckpointEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/git-deliveries/{deliveryID}": {
            "get": {
                "description": "按 deliveryID 查询 GitDelivery 详情，包含目标仓库、基础分支、工作分支、PR/MR 标题草稿、正文草稿、变更文件 JSON、验证摘要和交付状态。该接口用于交付审查页展示。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline"
                ],
                "summary": "获取单个交付记录详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "交付记录ID",
                        "name": "deliveryID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.GitDeliveryEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "健康检查"
                ],
                "summary": "服务健康检查",
                "responses": {}
            }
        },
        "/api/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "当前登录用户信息",
                "responses": {}
            }
        },
        "/api/pipeline-runs": {
            "get": {
                "description": "按创建时间倒序返回 PipelineRun 列表。前端工作台可用该接口展示所有研发流水线运行记录、当前阶段、运行状态、目标仓库和工作分支。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline"
                ],
                "summary": "获取流水线运行列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.PipelineRunListEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.ErrorEnvelope"
                        }
                    }
                }
            },
            "post": {
                "description": "通过自然语言需求创建一个新的 PipelineRun。服务端会按模板事务化初始化 StageRun、Checkpoint 和初始 Artifact，但不会自动开始执行；创建后需调用 start 接口进入队列。targetRepo 为空时默认 self，targetBranch 为空时默认 main。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline"
                ],
                "summary": "创建流水线运行",
                "parameters": [
                    {
                        "description": "json入参",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.CreatePipelineRunRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.PipelineRunDetailEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/pipeline-runs/from-session": {
            "post": {
                "description": "将已有需求会话中的消息和摘要汇总为 requirementText，并创建 PipelineRun。该接口用于把需求对话链路桥接到 DevFlow Pipeline，不会自动启动执行。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline"
                ],
                "summary": "从会话创建流水线运行",
                "parameters": [
                    {
                        "description": "json入参",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.CreatePipelineRunFromSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.PipelineRunDetailEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/pipeline-runs/{id}": {
            "get": {
                "description": "返回单个 PipelineRun 的基础详情，以及该运行下的 StageRun、Artifact 和 Checkpoint 列表。适合详情页初始化使用；若需要 AgentRun、GitDelivery、当前动作提示，请使用 timeline/current 接口。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline"
                ],
                "summary": "获取流水线运行详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "流水线运行ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.PipelineRunDetailEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/pipeline-runs/{id}/agent-runs": {
            "get": {
                "description": "返回指定 PipelineRun 的 AgentRun 列表。每条记录包含 AgentKey、Provider、Model、PromptSnapshot、输入输出、token usage 占位、耗时、状态和错误信息，用于审计真实 provider 调用、fallback 和阶段执行结果。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline"
                ],
                "summary": "获取流水线 Agent 执行记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "流水线运行ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.RunAgentRunListEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/pipeline-runs/{id}/artifacts": {
            "get": {
                "description": "返回指定 PipelineRun 的全部 Artifact。Artifact 是阶段间数据流转的核心载体，包含结构化需求、技术方案、代码变更计划、测试报告、评审报告和交付摘要等。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline"
                ],
                "summary": "获取流水线产物列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "流水线运行ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.RunArtifactListEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/pipeline-runs/{id}/checkpoints": {
            "get": {
                "description": "返回指定 PipelineRun 的人工检查点列表。当前默认模板包含方案审批和评审确认两个 Human-in-the-Loop 节点，支持 approve/reject 决策。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline"
                ],
                "summary": "获取流水线检查点列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "流水线运行ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.RunCheckpointListEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/pipeline-runs/{id}/current": {
            "get": {
                "description": "返回当前 PipelineRun 的主操作上下文，包括当前阶段、当前产物、当前 checkpoint、当前 AgentRun、最新 GitDelivery 和 nextAction。nextAction 可用于驱动前端主按钮和审批/交付面板。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline"
                ],
                "summary": "获取流水线当前阶段详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "流水线运行ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.PipelineRunCurrentEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/pipeline-runs/{id}/deliveries": {
            "get": {
                "description": "返回指定 PipelineRun 的 GitDelivery 交付草稿列表。当前实现只创建本地可审查的交付记录和 PR/MR 草稿，不执行 git push，也不创建远程 PR/MR。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline"
                ],
                "summary": "获取流水线交付记录列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "流水线运行ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.RunGitDeliveryListEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/pipeline-runs/{id}/pause": {
            "post": {
                "description": "将 queued 或 running 状态的 PipelineRun 暂停。暂停后后台执行器会停止继续推进后续阶段；已完成的阶段和产物不会被删除。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline"
                ],
                "summary": "暂停流水线运行",
                "parameters": [
                    {
                        "type": "string",
                        "description": "流水线运行ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.RunStatusEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/pipeline-runs/{id}/resume": {
            "post": {
                "description": "将 paused 或 failed 状态的 PipelineRun 重新置为 queued 并投递后台 runner。waiting_approval 状态不能通过 resume 绕过审批，必须调用 checkpoint approve/reject。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline"
                ],
                "summary": "恢复流水线运行",
                "parameters": [
                    {
                        "type": "string",
                        "description": "流水线运行ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.RunStatusEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/pipeline-runs/{id}/stages": {
            "get": {
                "description": "返回指定 PipelineRun 的全部 StageRun，包含阶段 key、类型、状态、尝试次数、输入输出 JSON、错误信息和开始/结束时间。用于展示阶段流转和调试单个阶段状态。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline"
                ],
                "summary": "获取流水线阶段列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "流水线运行ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.RunStageListEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/pipeline-runs/{id}/start": {
            "post": {
                "description": "将 draft 或 failed 状态的 PipelineRun 置为 queued 并投递后台 runner。执行器会顺序运行可执行阶段，遇到 checkpoint 时自动进入 waiting_approval。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline"
                ],
                "summary": "启动流水线运行",
                "parameters": [
                    {
                        "type": "string",
                        "description": "流水线运行ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.RunStatusEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/pipeline-runs/{id}/terminate": {
            "post": {
                "description": "将未完成的 PipelineRun 标记为 terminated。terminated 和 completed 都是终态，不能再次 start/resume；该接口不会删除已有产物、AgentRun 或交付记录。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline"
                ],
                "summary": "终止流水线运行",
                "parameters": [
                    {
                        "type": "string",
                        "description": "流水线运行ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.RunStatusEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/pipeline-runs/{id}/timeline": {
            "get": {
                "description": "聚合返回 PipelineRun、所有 StageRun、Artifact、Checkpoint、AgentRun、GitDelivery、当前阶段和 summary。summary 包含阶段统计、等待审批状态、最新产物、最新交付记录和耗时信息，是前端工作台的主数据接口。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline"
                ],
                "summary": "获取流水线工作台时间线",
                "parameters": [
                    {
                        "type": "string",
                        "description": "流水线运行ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.PipelineRunTimelineEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/pipeline-templates": {
            "get": {
                "description": "返回当前系统可用的 PipelineTemplate。模板定义了赛题要求的研发流水线阶段、顺序和 checkpoint，用于创建 PipelineRun 时初始化 StageRun、Checkpoint 和初始需求产物。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline"
                ],
                "summary": "获取流水线模板列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.PipelineTemplateListEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pipelinetype.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/sessions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "会话列表",
                "responses": {}
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "创建会话",
                "parameters": [
                    {
                        "description": "json入参",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sessiontype.CreateSessionRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/sessions/{sessionID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "会话详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/sessions/{sessionID}/messages": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "追加消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "json入参",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sessiontype.CreateMessageRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/sessions/{sessionID}/messages/stream": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "流式追加消息（SSE）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "json入参",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sessiontype.CreateMessageRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/sessions/{sessionID}/publish": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "发布会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/tasks/{taskID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务"
                ],
                "summary": "任务详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "taskID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/tasks/{taskID}/status": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务"
                ],
                "summary": "更新任务状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "taskID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "json入参",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tasktype.UpdateTaskStatusRequest"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "admintype.CreateRoleMappingRequest": {
            "type": "object",
            "required": [
                "keyword",
                "name",
                "role"
            ],
            "properties": {
                "departments": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "keyword": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/model.Role"
                }
            }
        },
        "admintype.KnowledgeSourceInput": {
            "type": "object",
            "required": [
                "content",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "admintype.SaveRoleOwnerRequest": {
            "type": "object",
            "required": [
                "ownerName",
                "role"
            ],
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "feishuId": {
                    "type": "string"
                },
                "feishuIdType": {
                    "type": "string"
                },
                "ownerName": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/model.Role"
                }
            }
        },
        "admintype.SyncKnowledgeRequest": {
            "type": "object",
            "required": [
                "sources"
            ],
            "properties": {
                "sources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admintype.KnowledgeSourceInput"
                    }
                }
            }
        },
        "authtype.FeishuSSOLoginRequest": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "model.AgentRunStatus": {
            "type": "string",
            "enum": [
                "pending",
                "running",
                "succeeded",
                "failed"
            ],
            "x-enum-varnames": [
                "AgentRunPending",
                "AgentRunRunning",
                "AgentRunSucceeded",
                "AgentRunFailed"
            ]
        },
        "model.ArtifactType": {
            "type": "string",
            "enum": [
                "structured_requirement",
                "solution_design",
                "code_diff",
                "test_report",
                "review_report",
                "delivery_summary"
            ],
            "x-enum-varnames": [
                "ArtifactStructuredRequirement",
                "ArtifactSolutionDesign",
                "ArtifactCodeDiff",
                "ArtifactTestReport",
                "ArtifactReviewReport",
                "ArtifactDeliverySummary"
            ]
        },
        "model.CheckpointStatus": {
            "type": "string",
            "enum": [
                "pending",
                "approved",
                "rejected"
            ],
            "x-enum-varnames": [
                "CheckpointPending",
                "CheckpointApproved",
                "CheckpointRejected"
            ]
        },
        "model.CheckpointType": {
            "type": "string",
            "enum": [
                "design_review",
                "code_review"
            ],
            "x-enum-varnames": [
                "CheckpointDesignReview",
                "CheckpointCodeReview"
            ]
        },
        "model.GitDeliveryStatus": {
            "type": "string",
            "enum": [
                "pending",
                "draft",
                "ready",
                "completed",
                "failed"
            ],
            "x-enum-varnames": [
                "GitDeliveryPending",
                "GitDeliveryDraft",
                "GitDeliveryReady",
                "GitDeliveryCompleted",
                "GitDeliveryFailed"
            ]
        },
        "model.PipelineRunStatus": {
            "type": "string",
            "enum": [
                "draft",
                "queued",
                "running",
                "waiting_approval",
                "paused",
                "failed",
                "completed",
                "terminated"
            ],
            "x-enum-varnames": [
                "PipelineRunDraft",
                "PipelineRunQueued",
                "PipelineRunRunning",
                "PipelineRunWaitingApproval",
                "PipelineRunPaused",
                "PipelineRunFailed",
                "PipelineRunCompleted",
                "PipelineRunTerminated"
            ]
        },
        "model.Role": {
            "type": "string",
            "enum": [
                "product",
                "frontend",
                "backend",
                "other",
                "admin"
            ],
            "x-enum-varnames": [
                "RoleProduct",
                "RoleFrontend",
                "RoleBackend",
                "RoleOther",
                "RoleAdmin"
            ]
        },
        "model.StageRunStatus": {
            "type": "string",
            "enum": [
                "pending",
                "queued",
                "running",
                "waiting_approval",
                "succeeded",
                "failed",
                "skipped"
            ],
            "x-enum-varnames": [
                "StageRunPending",
                "StageRunQueued",
                "StageRunRunning",
                "StageRunWaitingApproval",
                "StageRunSucceeded",
                "StageRunFailed",
                "StageRunSkipped"
            ]
        },
        "model.StageType": {
            "type": "string",
            "enum": [
                "analysis",
                "design",
                "checkpoint",
                "codegen",
                "test",
                "review",
                "delivery"
            ],
            "x-enum-varnames": [
                "StageTypeAnalysis",
                "StageTypeDesign",
                "StageTypeCheckpoint",
                "StageTypeCodegen",
                "StageTypeTest",
                "StageTypeReview",
                "StageTypeDelivery"
            ]
        },
        "model.TaskStatus": {
            "type": "string",
            "enum": [
                "todo",
                "in_progress",
                "testing",
                "done"
            ],
            "x-enum-varnames": [
                "TaskTodo",
                "TaskInProgress",
                "TaskTesting",
                "TaskDone"
            ]
        },
        "pipelinetype.AgentRunResponse": {
            "type": "object",
            "properties": {
                "agentKey": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "errorMessage": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inputJson": {
                    "type": "string"
                },
                "latencyMs": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "outputJson": {
                    "type": "string"
                },
                "pipelineRunId": {
                    "type": "string"
                },
                "promptSnapshot": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "stageRunId": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.AgentRunStatus"
                },
                "tokenUsageJson": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.ArtifactResponse": {
            "type": "object",
            "properties": {
                "artifactType": {
                    "$ref": "#/definitions/model.ArtifactType"
                },
                "contentJson": {
                    "type": "string"
                },
                "contentText": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "filePath": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metaJson": {
                    "type": "string"
                },
                "pipelineRunId": {
                    "type": "string"
                },
                "stageRunId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.CheckpointEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/pipelinetype.CheckpointResponse"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.CheckpointResponse": {
            "type": "object",
            "properties": {
                "approverId": {
                    "type": "string"
                },
                "checkpointType": {
                    "$ref": "#/definitions/model.CheckpointType"
                },
                "comment": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "decidedAt": {
                    "type": "string"
                },
                "decision": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "pipelineRunId": {
                    "type": "string"
                },
                "stageRunId": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.CheckpointStatus"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.CreatePipelineRunFromSessionRequest": {
            "type": "object",
            "required": [
                "sessionId"
            ],
            "properties": {
                "sessionId": {
                    "type": "string"
                },
                "targetBranch": {
                    "type": "string"
                },
                "targetRepo": {
                    "type": "string"
                },
                "templateId": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.CreatePipelineRunRequest": {
            "type": "object",
            "required": [
                "requirementText",
                "title"
            ],
            "properties": {
                "requirementText": {
                    "type": "string"
                },
                "targetBranch": {
                    "type": "string"
                },
                "targetRepo": {
                    "type": "string"
                },
                "templateId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.ErrorEnvelope": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.GitDeliveryEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/pipelinetype.GitDeliveryResponse"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.GitDeliveryResponse": {
            "type": "object",
            "properties": {
                "baseBranch": {
                    "type": "string"
                },
                "changedFilesJson": {
                    "type": "string"
                },
                "commitSha": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "headBranch": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "pipelineRunId": {
                    "type": "string"
                },
                "prmrBody": {
                    "type": "string"
                },
                "prmrTitle": {
                    "type": "string"
                },
                "prmrUrl": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "repo": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.GitDeliveryStatus"
                },
                "summaryMarkdown": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "validationJson": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.PipelineRunCurrentEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/pipelinetype.PipelineRunCurrentResponse"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.PipelineRunCurrentResponse": {
            "type": "object",
            "properties": {
                "agentRun": {
                    "$ref": "#/definitions/pipelinetype.AgentRunResponse"
                },
                "artifact": {
                    "$ref": "#/definitions/pipelinetype.ArtifactResponse"
                },
                "checkpoint": {
                    "$ref": "#/definitions/pipelinetype.CheckpointResponse"
                },
                "delivery": {
                    "$ref": "#/definitions/pipelinetype.GitDeliveryResponse"
                },
                "nextAction": {
                    "type": "string"
                },
                "run": {
                    "$ref": "#/definitions/pipelinetype.PipelineRunResponse"
                },
                "stage": {
                    "$ref": "#/definitions/pipelinetype.StageRunResponse"
                }
            }
        },
        "pipelinetype.PipelineRunDetailEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/pipelinetype.PipelineRunDetailResponse"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.PipelineRunDetailResponse": {
            "type": "object",
            "properties": {
                "artifacts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipelinetype.ArtifactResponse"
                    }
                },
                "checkpoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipelinetype.CheckpointResponse"
                    }
                },
                "run": {
                    "$ref": "#/definitions/pipelinetype.PipelineRunResponse"
                },
                "stages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipelinetype.StageRunResponse"
                    }
                }
            }
        },
        "pipelinetype.PipelineRunListEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipelinetype.PipelineRunResponse"
                    }
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.PipelineRunResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "string"
                },
                "currentStageKey": {
                    "type": "string"
                },
                "finishedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "requirementText": {
                    "type": "string"
                },
                "sourceSessionId": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.PipelineRunStatus"
                },
                "targetBranch": {
                    "type": "string"
                },
                "targetRepo": {
                    "type": "string"
                },
                "templateId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "workBranch": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.PipelineRunTimelineEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/pipelinetype.PipelineRunTimelineResponse"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.PipelineRunTimelineResponse": {
            "type": "object",
            "properties": {
                "agentRuns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipelinetype.AgentRunResponse"
                    }
                },
                "artifacts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipelinetype.ArtifactResponse"
                    }
                },
                "checkpoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipelinetype.CheckpointResponse"
                    }
                },
                "current": {
                    "$ref": "#/definitions/pipelinetype.PipelineRunCurrentResponse"
                },
                "deliveries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipelinetype.GitDeliveryResponse"
                    }
                },
                "run": {
                    "$ref": "#/definitions/pipelinetype.PipelineRunResponse"
                },
                "stages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipelinetype.StageRunResponse"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/pipelinetype.PipelineRunTimelineSummaryResponse"
                }
            }
        },
        "pipelinetype.PipelineRunTimelineSummaryResponse": {
            "type": "object",
            "properties": {
                "completedStages": {
                    "type": "integer"
                },
                "currentStageKey": {
                    "type": "string"
                },
                "durationMs": {
                    "type": "integer"
                },
                "failedStages": {
                    "type": "integer"
                },
                "finishedAt": {
                    "type": "string"
                },
                "latestArtifactId": {
                    "type": "string"
                },
                "latestDeliveryId": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "totalStages": {
                    "type": "integer"
                },
                "waitingApproval": {
                    "type": "boolean"
                }
            }
        },
        "pipelinetype.PipelineTemplateListEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipelinetype.PipelineTemplateResponse"
                    }
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.PipelineTemplateResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.RunAgentRunListEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/pipelinetype.RunAgentRunListResponse"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.RunAgentRunListResponse": {
            "type": "object",
            "properties": {
                "agentRuns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipelinetype.AgentRunResponse"
                    }
                }
            }
        },
        "pipelinetype.RunArtifactListEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/pipelinetype.RunArtifactListResponse"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.RunArtifactListResponse": {
            "type": "object",
            "properties": {
                "artifacts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipelinetype.ArtifactResponse"
                    }
                }
            }
        },
        "pipelinetype.RunCheckpointListEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/pipelinetype.RunCheckpointListResponse"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.RunCheckpointListResponse": {
            "type": "object",
            "properties": {
                "checkpoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipelinetype.CheckpointResponse"
                    }
                }
            }
        },
        "pipelinetype.RunGitDeliveryListEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/pipelinetype.RunGitDeliveryListResponse"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.RunGitDeliveryListResponse": {
            "type": "object",
            "properties": {
                "deliveries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipelinetype.GitDeliveryResponse"
                    }
                }
            }
        },
        "pipelinetype.RunStageListEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/pipelinetype.RunStageListResponse"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.RunStageListResponse": {
            "type": "object",
            "properties": {
                "stages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipelinetype.StageRunResponse"
                    }
                }
            }
        },
        "pipelinetype.RunStatusEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/pipelinetype.RunStatusResponse"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.RunStatusResponse": {
            "type": "object",
            "properties": {
                "currentStageKey": {
                    "type": "string"
                },
                "finishedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.PipelineRunStatus"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.StageRunResponse": {
            "type": "object",
            "properties": {
                "attempt": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "errorMessage": {
                    "type": "string"
                },
                "finishedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inputJson": {
                    "type": "string"
                },
                "outputJson": {
                    "type": "string"
                },
                "pipelineRunId": {
                    "type": "string"
                },
                "stageKey": {
                    "type": "string"
                },
                "stageType": {
                    "$ref": "#/definitions/model.StageType"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.StageRunStatus"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "pipelinetype.UpdateCheckpointDecisionRequest": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                }
            }
        },
        "sessiontype.CreateMessageRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "sessiontype.CreateSessionRequest": {
            "type": "object",
            "required": [
                "prompt",
                "title"
            ],
            "properties": {
                "prompt": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "tasktype.UpdateTaskStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "$ref": "#/definitions/model.TaskStatus"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Feishu Pipeline API",
	Description:      "Feishu Pipeline 后端 API 文档。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
