package pipeline

const (
	SchemaFieldSummary              = "summary"
	SchemaFieldGoals                = "goals"
	SchemaFieldNonGoals             = "nonGoals"
	SchemaFieldAcceptanceCriteria   = "acceptanceCriteria"
	SchemaFieldQuestions            = "questions"
	SchemaFieldImpactFiles          = "impactFiles"
	SchemaFieldAPIChanges           = "apiChanges"
	SchemaFieldDataModelChanges     = "dataModelChanges"
	SchemaFieldImplementationPlan   = "implementationPlan"
	SchemaFieldChangedFiles         = "changedFiles"
	SchemaFieldPatches              = "patches"
	SchemaFieldDiffSummary          = "diffSummary"
	SchemaFieldManualSteps          = "manualSteps"
	SchemaFieldTestPlan             = "testPlan"
	SchemaFieldCommands             = "commands"
	SchemaFieldCommandResults       = "commandResults"
	SchemaFieldStatus               = "status"
	SchemaFieldConclusion           = "conclusion"
	SchemaFieldIssues               = "issues"
	SchemaFieldSecurityNotes        = "securityNotes"
	SchemaFieldMaintainabilityNotes = "maintainabilityNotes"
	SchemaFieldTestCoverageNotes    = "testCoverageNotes"
	SchemaFieldValidation           = "validation"
	SchemaFieldPRTitle              = "prTitle"
	SchemaFieldPRBody               = "prBody"
	SchemaFieldManualReleaseNotes   = "manualReleaseNotes"
)
